changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"
