name: レビュー環境の削除

# develop branch に対する Pull Request が close された場合に実行
on:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  delete-review:
    name: レビュー環境の削除

    permissions:
      contents: read
      id-token: write
      pull-requests: write

    runs-on: ubuntu-latest

    env:
      GCP_WORKLOAD_IDENTITY_PROVIDER: projects/181168524791/locations/global/workloadIdentityPools/ssg-example/providers/gh-ssg-example
      GCP_SERVICE_ACCOUNT: gha-ssg-example@teraoka-test-331901.iam.gserviceaccount.com
      BUCKET_NAME: ssg-example-review-n9k0

    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ env.GCP_SERVICE_ACCOUNT }}

      # gsutil は Workload Identity Federation に対応していないため gcloud alpha storage を使用
      - name: Delete files from GCS
        run: |
          gcloud alpha storage rm -r gs://${BUCKET_NAME}/pr-${{ github.event.pull_request.number }} || true

      - name: URL を書き込む既存のコメントを検索
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: レビュー用の URL です

      # find-comment で見つからなければ skip
      - name: Pull Request のコメントに URL を追加
        if: steps.fc.outputs.comment-id != ''
        uses: peter-evans/create-or-update-comment@v3
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ github.event.pull_request.number }}
          edit-mode: replace
          body: |
            レビュー用の URL です (削除済み)
            ~https://storage.googleapis.com/${{ env.BUCKET_NAME }}/pr-${{ github.event.pull_request.number }}/index.html~
